// DO NOT EDIT!
// Automatically generated from xbb-helper/templates/docusaurus/common.

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'doc',
      id: 'getting-started/index',
      label: 'Getting Started'
    },
    {
      type: 'doc',
      id: 'about/index',
      label: 'About'
    },
  ],
  toolsSidebar: [
    {
      type: 'doc',
      label: 'Tools',
      id: 'tools/index'
    },
    {
      type: 'category',
      label: 'Main Tools',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'xPack GNU AArch64 Embedded GCC',
          href: 'https://xpack-dev-tools.github.io/aarch64-none-elf-gcc-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU Arm Embedded GCC',
          href: 'https://xpack-dev-tools.github.io/arm-none-eabi-gcc-xpack/',
        },
        {
          type: 'link',
          label: 'xPack LLVM clang',
          href: 'https://xpack-dev-tools.github.io/clang-xpack/',
        },
        {
          type: 'link',
          label: 'xPack CMake',
          href: 'https://xpack-dev-tools.github.io/cmake-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU GCC',
          href: 'https://xpack-dev-tools.github.io/gcc-xpack/',
        },
        {
          type: 'link',
          label: 'xPack Meson Build',
          href: 'https://xpack-dev-tools.github.io/meson-build-xpack/',
        },
        {
          type: 'link',
          label: 'xPack MinGW-w64 GCC',
          href: 'https://xpack-dev-tools.github.io/mingw-w64-gcc-xpack/',
        },
        {
          type: 'link',
          label: 'xPack Ninja Build',
          href: 'https://xpack-dev-tools.github.io/ninja-build-xpack/',
        },
        {
          type: 'link',
          label: 'xPack OpenOCD',
          href: 'https://xpack-dev-tools.github.io/openocd-xpack/',
        },
        {
          type: 'link',
          label: 'xPack QEMU Arm',
          href: 'https://xpack-dev-tools.github.io/qemu-arm-xpack/',
        },
        {
          type: 'link',
          label: 'xPack QEMU RISC-V',
          href: 'https://xpack-dev-tools.github.io/qemu-riscv-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU RISC-V Embedded GCC',
          href: 'https://xpack-dev-tools.github.io/riscv-none-elf-gcc-xpack/',
        },
        {
          type: 'link',
          label: 'xPack Windows Build Tools',
          href: 'https://xpack-dev-tools.github.io/windows-build-tools-xpack/',
        },
      ]
    },
    {
      type: 'category',
      label: 'Supplementary Tools',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'xPack bison',
          href: 'https://xpack-dev-tools.github.io/bison-xpack/',
        },
        {
          type: 'link',
          label: 'xPack flex',
          href: 'https://xpack-dev-tools.github.io/flex-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU m4',
          href: 'https://xpack-dev-tools.github.io/m4-xpack/',
        },
        {
          type: 'link',
          label: 'xPack NixOS PatchELF',
          href: 'https://xpack-dev-tools.github.io/patchelf-xpack/',
        },
        {
          type: 'link',
          label: 'xPack pkg-config',
          href: 'https://xpack-dev-tools.github.io/pkg-config-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU realpath',
          href: 'https://xpack-dev-tools.github.io/realpath-xpack/',
        },
        {
          type: 'link',
          label: 'xPack GNU sed',
          href: 'https://xpack-dev-tools.github.io/sed-xpack/',
        },
        {
          type: 'link',
          label: 'xPack WineHQ',
          href: 'https://xpack-dev-tools.github.io/wine-xpack/',
        },
      ]
    },
  ]
};

export default sidebars;
